### ISSUE TITLE
batchsize problem

### ISSUE THREAD

**Issue by lipond** [douzi0248/Re-ID#2]
After I modified batchsize from 32 to 64, the training outputs following errors.

Traceback (most recent call last):
  File "train_11.py", line 333, in <module>
    num_epochs=320)
  File "train_11.py", line 189, in train_model
    loss5 =  triplet(q1, labels)[0]
  File "/data1/sanjie.lp/projects/person_reid/Re-ID-douzi0248/triplet_loss.py", line 110, in __call__
    dist_mat, labels)
  File "/data1/sanjie.lp/projects/person_reid/Re-ID-douzi0248/triplet_loss.py", line 66, in hard_example_mining
    dist_mat[is_pos].contiguous().view(N, -1), 1, keepdim=True)
RuntimeError: invalid argument 2: size '[64 x -1]' is invalid for input with 288 elements at /pytorch/aten/src/TH/THStorage.cpp:80

**Comment by douzi0248** [comment]
You should also modify batchsize in the dataloaders.

**Comment by lipond** [comment]
Thanks, it solved my problem.
